[project]
name = "snakes-and-ladders"
version = "0.0.1"
description = "Experimental code"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.15.0",
    "ruff>=0.11.11",
]

[tool.distutils.egg_info]
egg_base = "."

[tool.setuptools]
packages = ["game"]
